development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: jc_dev
  pool: 5
  username: root
  password: In2Teck2010
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: jc_test
  pool: 5
  username: root
  password: In2Teck2010
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: jc_prod
  pool: 5
  username: root
  password: In2Teck2010
  host: localhost
