development:
  adapter: mysql
  encoding: utf8
  reconnect: true
  database: jc_dev
  pool: 15
  username: rails
  password: t2omedia
  host: localhost

test:
  adapter: mysql
  encoding: utf8
  reconnect: true
  database: jc_test
  pool: 15
  username: rails
  password: t2omedia
  host: localhost

production:
  adapter: mysql
  encoding: utf8
  reconnect: true
  database: jc_prod
  pool: 15
  username: rails
  password: t2omedia
  host: localhost
